-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 13:32:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_forClass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_forClass` ;

-- -----------------------------------------------------
-- Schema db_forClass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_forClass` DEFAULT CHARACTER SET utf8 ;
USE `db_forClass` ;

-- -----------------------------------------------------
-- Table `db_forClass`.`tblUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblUser` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblUser` (
  `idtblUser` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `FullName` VARCHAR(201) GENERATED ALWAYS AS (CONCAT(FirstName,' ',LastName)) STORED,
  `Dob` DATE NOT NULL,
  `Salt` CHAR(64) NOT NULL,
  `UUID` CHAR(32) NOT NULL,
  `RegisterDateTime` DATETIME NOT NULL,
  `isDeleted` TINYINT NULL,
  PRIMARY KEY (`idtblUser`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Salt_UNIQUE` (`Salt` ASC) VISIBLE,
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblUserCredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblUserCredential` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblUserCredential` (
  `idtblUserCredential` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `HashedPwd` VARCHAR(512) NOT NULL,
  `CreateDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idtblUserCredential`, `UserID`),
  UNIQUE INDEX `HashedPwd_UNIQUE` (`HashedPwd` ASC) VISIBLE,
  INDEX `fkUserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fkUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_forClass`.`tblUser` (`idtblUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblCity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblCity` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblCity` (
  `idtblCity` INT UNSIGNED NOT NULL,
  `CityName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtblCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblDistrict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblDistrict` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblDistrict` (
  `idtblDistrict` INT UNSIGNED NOT NULL,
  `CityID` INT UNSIGNED NOT NULL,
  `DistrictName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtblDistrict`, `CityID`),
  INDEX `fkCityID_idx` (`CityID` ASC) VISIBLE,
  CONSTRAINT `fkCityID`
    FOREIGN KEY (`CityID`)
    REFERENCES `db_forClass`.`tblCity` (`idtblCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblOrder` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblOrder` (
  `idtlbOrder` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `CreateDateTime` DATETIME NOT NULL,
  `OrderTotal` MEDIUMINT(6) UNSIGNED NOT NULL,
  `Delivery_city` INT UNSIGNED NOT NULL,
  `Delivery_district` INT UNSIGNED NOT NULL,
  `Delivery_address_line` CHAR(200) NOT NULL,
  PRIMARY KEY (`idtlbOrder`),
  INDEX `fkUserID_OrderID_idx` (`UserID` ASC) VISIBLE,
  INDEX `fkDiliveryCity_idx` (`Delivery_city` ASC) VISIBLE,
  INDEX `fkDeliveryDistrict_idx` (`Delivery_district` ASC) VISIBLE,
  CONSTRAINT `fkUserID_OrderID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_forClass`.`tblUser` (`idtblUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDeliveryCity`
    FOREIGN KEY (`Delivery_city`)
    REFERENCES `db_forClass`.`tblCity` (`idtblCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDeliveryDistrict`
    FOREIGN KEY (`Delivery_district`)
    REFERENCES `db_forClass`.`tblDistrict` (`idtblDistrict`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblItem` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblItem` (
  `idtlbItem` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(512) NOT NULL,
  `Price` MEDIUMINT(6) UNSIGNED NOT NULL,
  `isOffShelf` TINYINT NULL,
  PRIMARY KEY (`idtlbItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblOrderItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblOrderItems` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblOrderItems` (
  `tlbOrder_idtlbOrder` INT NOT NULL,
  `tlbItem_idtlbItem` INT NOT NULL,
  `ItemQuanity` INT(4) UNSIGNED NOT NULL,
  `ItemPrice` MEDIUMINT(6) UNSIGNED NOT NULL,
  INDEX `fk_tlbOrder_has_tlbItem_tlbItem1_idx` (`tlbItem_idtlbItem` ASC) VISIBLE,
  INDEX `fk_tlbOrder_has_tlbItem_tlbOrder1_idx` (`tlbOrder_idtlbOrder` ASC) VISIBLE,
  PRIMARY KEY (`tlbOrder_idtlbOrder`),
  CONSTRAINT `fk_tlbOrder_has_tlbItem_tlbOrder1`
    FOREIGN KEY (`tlbOrder_idtlbOrder`)
    REFERENCES `db_forClass`.`tblOrder` (`idtlbOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tlbOrder_has_tlbItem_tlbItem1`
    FOREIGN KEY (`tlbItem_idtlbItem`)
    REFERENCES `db_forClass`.`tblItem` (`idtlbItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblShoppingCart` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblShoppingCart` (
  `UserID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  `Quenity` INT(4) UNSIGNED NOT NULL,
  INDEX `fkItemID_idx` (`ItemID` ASC) VISIBLE,
  CONSTRAINT `fkUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_forClass`.`tblUser` (`idtblUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `db_forClass`.`tblItem` (`idtlbItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblWishList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblWishList` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblWishList` (
  `UserID` INT NOT NULL,
  `ItemID` INT NOT NULL,
  INDEX `fkWishList_UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fkWishList_UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_forClass`.`tblUser` (`idtblUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkWishList_ItemID`
    FOREIGN KEY (`ItemID`)
    REFERENCES `db_forClass`.`tblItem` (`idtlbItem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`ItemStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`ItemStock` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`ItemStock` (
  `idItemStock` INT NOT NULL,
  `StockQuanity` INT(4) UNSIGNED NOT NULL,
  `SupplierName` VARCHAR(200) NULL,
  `SupplierPhoneNumber` VARCHAR(15) NULL,
  PRIMARY KEY (`idItemStock`),
  CONSTRAINT `fkStock_form_Item`
    FOREIGN KEY (`idItemStock`)
    REFERENCES `db_forClass`.`tblItem` (`idtlbItem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
