-- MySQL Script generated by MySQL Workbench
-- Fri Jun 21 01:07:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_106403551
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_106403551` ;

-- -----------------------------------------------------
-- Schema DB_106403551
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_106403551` DEFAULT CHARACTER SET utf8 ;
USE `db_106403551` ;

-- -----------------------------------------------------
-- Table `DB_106403551`.`tblUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblUser` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblUser` (
  `idtblUser` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `FullName` VARCHAR(201) GENERATED ALWAYS AS (CONCAT(FirstName,' ',LastName)) STORED,
  `Dob` DATE NOT NULL,
  `Salt` CHAR(64) NOT NULL,
  `UUID` VARCHAR(40) NOT NULL,
  `RegisterDateTime` DATETIME NOT NULL,
  `isDeleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idtblUser`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `Salt_UNIQUE` (`Salt` ASC),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblUserCredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblUserCredential` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblUserCredential` (
  `idtblUserCredential` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `HashedPwd` VARCHAR(512) NOT NULL,
  `CreateDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idtblUserCredential`, `UserID`),
  UNIQUE INDEX `HashedPwd_UNIQUE` (`HashedPwd` ASC),
  INDEX `fkUserID_idx` (`UserID` ASC),
  CONSTRAINT `fkUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_106403551`.`tblUser` (`idtblUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblCity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblCity` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblCity` (
  `idtblCity` INT UNSIGNED NOT NULL,
  `CityName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtblCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblDistrict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblDistrict` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblDistrict` (
  `idtblDistrict` INT UNSIGNED NOT NULL,
  `CityID` INT UNSIGNED NOT NULL,
  `DistrictName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtblDistrict`, `CityID`),
  INDEX `fkCityID_idx` (`CityID` ASC),
  CONSTRAINT `fkCityID`
    FOREIGN KEY (`CityID`)
    REFERENCES `db_106403551`.`tblCity` (`idtblCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblOrder` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblOrder` (
  `idtlbOrder` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `CreateDateTime` DATETIME NOT NULL,
  `OrderTotal` MEDIUMINT(6) UNSIGNED NOT NULL,
  `Delivery_city` INT UNSIGNED NOT NULL,
  `Delivery_district` INT UNSIGNED NOT NULL,
  `Delivery_address_line` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idtlbOrder`),
  INDEX `fkUserID_OrderID_idx` (`UserID` ASC),
  INDEX `fkDiliveryCity_idx` (`Delivery_city` ASC),
  INDEX `fkDeliveryDistrict_idx` (`Delivery_district` ASC),
  CONSTRAINT `fkUserID_OrderID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_106403551`.`tblUser` (`idtblUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDeliveryCity`
    FOREIGN KEY (`Delivery_city`)
    REFERENCES `db_106403551`.`tblCity` (`idtblCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkDeliveryDistrict`
    FOREIGN KEY (`Delivery_district`)
    REFERENCES `db_106403551`.`tblDistrict` (`idtblDistrict`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblItem` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblItem` (
  `idtlbItem` INT NOT NULL AUTO_INCREMENT,
  `ItemName` VARCHAR(512) NOT NULL,
  `Price` MEDIUMINT(6) UNSIGNED NOT NULL,
  `ItemDescription` VARCHAR(300) NULL,
  `isOffShelf` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idtlbItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblOrderItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblOrderItems` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblOrderItems` (
  `pk` INT NOT NULL AUTO_INCREMENT,
  `Order_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  `ItemQuanity` INT(4) UNSIGNED NOT NULL,
  `ItemPrice` MEDIUMINT(6) UNSIGNED NOT NULL,
  INDEX `fk_tlbOrder_has_tlbItem_tlbItem1_idx` (`Item_id` ASC),
  INDEX `fk_tlbOrder_has_tlbItem_tlbOrder1_idx` (`Order_id` ASC),
  PRIMARY KEY (`pk`),
  CONSTRAINT `fk_tlbOrder_has_tlbItem_tlbOrder1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `db_106403551`.`tblOrder` (`idtlbOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tlbOrder_has_tlbItem_tlbItem1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `db_106403551`.`tblItem` (`idtlbItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblShoppingCart` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblShoppingCart` (
  `Cart_id` INT NOT NULL AUTO_INCREMENT,
  `UserID_Cart` INT NOT NULL,
  `ItemID_Cart` INT NOT NULL,
  `Quenity_Cart` INT(4) UNSIGNED NOT NULL,
  `isDeleted` INT(1) NULL DEFAULT 0,
  INDEX `fkItemID_idx` (`ItemID_Cart` ASC),
  PRIMARY KEY (`Cart_id`),
  CONSTRAINT `fkUserID_Cart`
    FOREIGN KEY (`UserID_Cart`)
    REFERENCES `db_106403551`.`tblUser` (`idtblUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkItemID_Cart`
    FOREIGN KEY (`ItemID_Cart`)
    REFERENCES `db_106403551`.`tblItem` (`idtlbItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`tblWishList`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`tblWishList` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`tblWishList` (
  `WishList_id` INT NOT NULL AUTO_INCREMENT,
  `UserID_Wish` INT NOT NULL,
  `ItemID_Wish` INT NOT NULL,
  `isDeleted` INT(1) NULL DEFAULT 0,
  INDEX `fkWishList_UserID_idx` (`UserID_Wish` ASC),
  PRIMARY KEY (`WishList_id`),
  CONSTRAINT `fkWishList_UserID`
    FOREIGN KEY (`UserID_Wish`)
    REFERENCES `db_106403551`.`tblUser` (`idtblUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkWishList_ItemID`
    FOREIGN KEY (`ItemID_Wish`)
    REFERENCES `db_106403551`.`tblItem` (`idtlbItem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_106403551`.`ItemStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_106403551`.`ItemStock` ;

CREATE TABLE IF NOT EXISTS `db_106403551`.`ItemStock` (
  `idItemStock` INT NOT NULL,
  `StockQuanity` INT(4) UNSIGNED NOT NULL,
  `SupplierName` VARCHAR(200) NULL,
  `SupplierPhoneNumber` VARCHAR(15) NULL,
  PRIMARY KEY (`idItemStock`),
  CONSTRAINT `fkStock_form_Item`
    FOREIGN KEY (`idItemStock`)
    REFERENCES `db_106403551`.`tblItem` (`idtlbItem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
