-- MySQL Script generated by MySQL Workbench
-- Fri May 24 15:22:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_forClass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_forClass` ;

-- -----------------------------------------------------
-- Schema db_forClass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_forClass` DEFAULT CHARACTER SET utf8 ;
USE `db_forClass` ;

-- -----------------------------------------------------
-- Table `db_forClass`.`tblUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblUser` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblUser` (
  `idtblUser` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(200) NOT NULL,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `FullName` VARCHAR(201) GENERATED ALWAYS AS (CONCAT(FirstName,' ',LastName)) STORED,
  `Dob` DATE NOT NULL,
  `Salt` CHAR(64) NOT NULL,
  `UUID` CHAR(32) NOT NULL,
  `RegisterDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`idtblUser`),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) ,
  UNIQUE INDEX `Salt_UNIQUE` (`Salt` ASC) ,
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_forClass`.`tblUserCredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_forClass`.`tblUserCredential` ;

CREATE TABLE IF NOT EXISTS `db_forClass`.`tblUserCredential` (
  `idtblUserCredential` INT NOT NULL AUTO_INCREMENT,
  `HashedPwd` VARCHAR(512) NOT NULL,
  `CreateDateTime` DATETIME NULL,
  `UserID` INT NULL,
  PRIMARY KEY (`idtblUserCredential`),
  UNIQUE INDEX `HashedPwd_UNIQUE` (`HashedPwd` ASC) ,
  INDEX `fkUserID_idx` (`UserID` ASC) ,
  CONSTRAINT `fkUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `db_forClass`.`tblUser` (`idtblUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
